import React from 'react'

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"


export function Accordionfg() {
  return (
    <Accordion type="single" collapsible className="w-full ">
      <AccordionItem value="item-1">
        <AccordionTrigger className='text-lg'>What is FoundrGuide?</AccordionTrigger>
        <AccordionContent className='text-base'>
        FoundrGuide is an AI-powered platform designed to provide personalized business advice and book summaries tailored to the specific needs of startup founders. By leveraging insights from top business books and expert strategies, FoundrGuide acts as your virtual mentor, helping you overcome challenges and grow your business.
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="item-2">
        <AccordionTrigger className='text-lg'> How does FoundrGuide provide tailored advice?</AccordionTrigger>
        <AccordionContent className='text-base'>
        Our platform uses advanced AI models to analyze your questions and challenges, then draws from a library of expert business books and articles. The AI delivers personalized advice based on the most relevant insights, tailored to your startup’s unique needs.
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="item-3">
        <AccordionTrigger className='text-lg'>Can I choose the books I want advice from?</AccordionTrigger>
        <AccordionContent className='text-base'>
        Yes, you can either let our AI select the most relevant books based on your query, or you can browse and choose from a list of summarized books in various categories like leadership, marketing, and startup growth.
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="item-4">
        <AccordionTrigger className='text-lg'> Is the advice generated by FoundrGuide really helpful for my startup?</AccordionTrigger>
        <AccordionContent className='text-base'>
        Absolutely! The advice is drawn from leading business books and expert content specifically curated to help entrepreneurs and startup founders. The AI tailors solutions based on your exact business challenges, providing actionable strategies to support your growth.
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="item-5">
        <AccordionTrigger className='text-lg'>Can I ask follow-up questions or dive deeper into specific topics?</AccordionTrigger>
        <AccordionContent className='text-base'>
        Yes! After receiving your initial advice or book summary, you can ask follow-up questions or request a deeper dive into specific topics to get more detailed insights and strategies.
        </AccordionContent>
      </AccordionItem>
    </Accordion>
  )
}

export default function Faq() {
  return (
    <div className="w-full min-h-full mx-auto p-4 md:p-10 text-center bg-gradient-to-b from-white via-white to-blue-100/50">
      <div className="flex flex-col px-4 md:px-28 py-8 md:py-16 mx-auto">
        <h2 className='text-3xl md:text-4xl font-semibold bg-gradient-to-bl from-blue-500 to-blue-700 bg-clip-text text-transparent'>Frequently Asked Questions!</h2>
        <p className="text-sm text-start px-2 md:px-4 py-1 mt-6 md:mt-10">
          <span className="bg-blue-100 px-3 py-1 items-center ml-2 md:ml-5 text-blue-800 rounded-2xl">
            WE&apos;VE GOT ANSWERS
          </span>
        </p>
        <div className='flex flex-wrap min-w-fit text-start p-4 md:p-10'>
          <Accordionfg /> 
        </div>
      </div>
    </div>
  )
}


